# Generated by Django 4.1.3 on 2022-11-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantharooapp', '0002_allowdevice_notallow'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowdevice',
            name='ApplicationName',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='ApplicationName',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='notallow',
            name='ApplicationName',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
