# Generated by Django 4.1.3 on 2022-11-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantharooapp', '0003_allowdevice_applicationname_history_applicationname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableFiles',
            fields=[
                ('slNo', models.AutoField(primary_key=True, serialize=False)),
                ('FileCreaterFullName', models.CharField(max_length=122)),
                ('FileCreaterApplicationName', models.CharField(max_length=122, null=True)),
                ('FileCreaterEmployeeID', models.IntegerField()),
                ('FileCreaterEmail', models.CharField(max_length=122)),
                ('FileCreaterDesktopID', models.CharField(max_length=122)),
                ('FileCreaterIP_Address', models.CharField(max_length=100)),
                ('fileNameData', models.CharField(max_length=300)),
                ('MainDateTime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('slNo', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=122)),
                ('ApplicationName', models.CharField(max_length=122, null=True)),
                ('EmployeeID', models.IntegerField()),
                ('Email', models.CharField(max_length=122)),
                ('DesktopID', models.CharField(max_length=122)),
                ('IP_Address', models.CharField(max_length=100)),
                ('fileNameData', models.CharField(max_length=300)),
                ('MainDateTime', models.DateField(auto_now=True)),
            ],
        ),
    ]
