# Generated by Django 4.1.3 on 2022-11-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantharooapp', '0004_availablefiles_filehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileHistoryNotAllowSPAM',
            fields=[
                ('slNo', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=122)),
                ('ApplicationName', models.CharField(max_length=122, null=True)),
                ('EmployeeID', models.IntegerField()),
                ('Email', models.CharField(max_length=122)),
                ('DesktopID', models.CharField(max_length=122)),
                ('IP_Address', models.CharField(max_length=100)),
                ('fileNameData', models.CharField(max_length=300)),
                ('MainDateTime', models.DateField(auto_now=True)),
            ],
        ),
    ]
